chore: support linux gcc build env
- gcc requires `-pthread` as explicit link option
- Original implementation causes the following link error:

```
/usr/bin/ld: capnproto-1.1.0/lib/libkj-async.a(async-unix.o): in function `kj::UnixEventPort::registerSignalHandler(int)':
async-unix.c++:(.text+0x14e8): undefined reference to `pthread_sigmask'
/usr/bin/ld: capnproto-1.1.0/lib/libkj.a(thread.o): in function `kj::Thread::sendSignal(int)':
thread.c++:(.text+0x4e): undefined reference to `pthread_kill'
/usr/bin/ld: capnproto-1.1.0/lib/libkj.a(thread.o): in function `kj::Thread::Thread(kj::Function<void ()>)':
thread.c++:(.text+0x334): undefined reference to `pthread_create'
/usr/bin/ld: capnproto-1.1.0/lib/libkj.a(thread.o): in function `kj::Thread::detach()':
thread.c++:(.text+0x3f2): undefined reference to `pthread_detach'
/usr/bin/ld: capnproto-1.1.0/lib/libkj.a(thread.o): in function `kj::Thread::~Thread()':
thread.c++:(.text+0x58a): undefined reference to `pthread_join'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/capnp-ls.dir/build.make:224: capnp-ls] Error 1
make[1]: *** [CMakeFiles/Makefile2:78: CMakeFiles/capnp-ls.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```